version: "3.8"

services:
  app:
    build: ./btc-tracker
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true